---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi-config
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 512Mi