---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: unifi
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://kubernetes.github.io/ingress-nginx
      chart: unifi
      version: 4.0.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  values:
    env:
      TZ: 'Ireland/Dublin'
    service:
      lb:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: 10.0.1.104
        ports:
          stun:
            enabled: true
            port: 3478
            protocol: UDP
          syslog:
            enabled: true
            port: 5514
            protocol: UDP
          discovery:
            enabled: true
            port: 10001
            protocol: UDP
          https:
            enabled: true
            port: 443
            protocol: TCP
          http:
            enabled: true
            port: 8080
            protocol: TCP
          http2:
            enabled: true
            port: 8883
            protocol: TCP
          http2:
            enabled: true
            port: 8443
            protocol: TCP