---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: unifi
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://kubernetes.github.io/ingress-nginx
      chart: unifi
      version: 4.0.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  values:
    env:
      TZ: 'Ireland/Dublin'
    service:
      lb:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: 10.0.1.104
        externalTrafficPolicy: Local
        ports:
          httplb:
            enabled: true
            port: 8443
            protocol: HTTPS
          controllerlb:
            enabled: true
            port: 8080
            protocol: TCP
          portal-httplb:
            enabled: false
            port: 8880
            protocol: HTTP
          portal-httpslb:
            enabled: false
            port: 8843
            protocol: HTTPS
          speedtestlb:
            enabled: true
            port: 6789
            protocol: TCP
          stunlb:
            enabled: true
            port: 3478
            protocol: UDP
          sysloglb:
            enabled: true
            port: 5514
            protocol: UDP
          discoverylb:
            enabled: true
            port: 10001
            protocol: UDP
    persistence:
      config:
        enabled: true
        existingClaim: unifi-config
        mountPath: /var/lib/unifi