---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jackett
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: jackett
      version: 11.0.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  values:
    env:
      TZ: "Europe/London"
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: "${JACKETT_LB}"
        enabled: true
    persistence:
      config:
        enabled: true
        existingClaim: jackett-config
        mountPath: /config
