# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: tomnuc.home
    SECRET_CLOUDFLARE_EMAIL: ashley.deane.93@gmail.com
