---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
  name: udp-services
  namespace: networking
data:
  53: "default/adguard-home:53"