---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: home-assistant
      version: 10.0.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  values:
    service:
      main:
        enabled: true
      lb:
        type: LoadBalancer
        loadBalancerIP: "${HOME_ASSISTANT_LB}"
        externalTrafficPolicy: Local
        enabled: true
        ports:
          http-lb:
            enabled: true
            port: 8123
            protocol: HTTP
    persistence:
      config:
        enabled: true
        existingClaim: hass-config
        mountPath: /config
    addons:
      codeserver:
        enabled: true
        image:
          repository: codercom/code-server
          tag: 3.9.0
        workingDir: "/config"
        args:
        - --auth
        - "none"
        - --user-data-dir
        - "/config/.vscode"
        - --extensions-dir
        - "/config/.vscode"
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: "nginx"
          hosts:
          - host: "code.home.${SECRET_DOMAIN}"
            paths:
            - path: /
              pathType: Prefix
          tls:
          - hosts:
            - "code.home.${SECRET_DOMAIN}"
        volumeMounts:
        - name: config
          mountPath: /config
