---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: overseerr
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: overseerr
      version: 5.0.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  values:
    env:
      TZ: "Europe/London"
    service:
      main:
        enabled: true
      lb:
        type: LoadBalancer
        loadBalancerIP: "${OVERSEERR_LB}"
        externalTrafficPolicy: Local
        enabled: true
        ports:
          http-lb:
            enabled: true
            port: 5055
            protocol: HTTP
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
        hosts:
          - host: "overseerr.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "overseerr.${SECRET_DOMAIN}"
    persistence:
      config:
        enabled: true
        existingClaim: overseerr-config
        mountPath: /app/config
